export {default as Navbar} from "./Navbar/Navbar.jsx"
export {default as Hero} from "./Hero/Hero.jsx"
export {default as ConnectSection} from "./ConnectSection/ConnectSection.jsx"
export {default as GatitosCards} from "./GatitosCards/GatitosCards.jsx"
export {default as Gatitos} from "./Gatitos/Gatitos.jsx"
export {default as Footer} from "./Footer/Footer.jsx"
export {default as Video} from "./Video/Video.jsx"
