export {default as Navbar} from "./Navbar/Navbar.jsx"
export {default as Hero} from "./Hero/Hero.jsx"
export {default as Pricing} from "./Pricing/Pricing.jsx"
export {default as Features} from "./Features/Features.jsx"
export {default as Footer} from "./Footer/Footer.jsx"
export {default as Testimonials} from "./Testimonials/Testimonials.jsx"